name = "meilv-web"
compatibility_date = "2025-08-31"

# Assets 配置 - 指向构建输出目录
[assets]
directory = ".next"

# 环境变量
[vars]
NODE_ENV = "production"

# 生产环境配置
[env.production]
name = "meilv-web-prod"

[env.production.vars]
NODE_ENV = "production"
