# Cloudflare Pages 配置
# 此项目应该使用 Cloudflare Pages 而不是 Workers
# 请在 Cloudflare Dashboard 中使用 Pages 服务进行部署

name = "meilv-web"
compatibility_date = "2025-08-31"

# 这个文件仅用于 Cloudflare Workers
# 对于 Next.js 应用，请使用 Cloudflare Pages
