# Cloudflare Pages 配置
name = "meilv-web"
compatibility_date = "2025-08-31"

# Pages 构建输出目录
pages_build_output_dir = "out"

# 排除大文件和缓存
[build]
command = "npm run build"
cwd = ""

# 环境变量
[env.production]
NODE_VERSION = "20"
